name: AMS Build

on:
  # push:
    # branches: [ "*" ]
  # pull_request:
    # branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

permissions: write-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'
      ##image: 'ghcr.io/irneracoonovich/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # - name: pacman  do not do this!!!!
        # run: | 
          # dkp-pacman -Syuu
          # dkp-pacman -Sy switch-dev switch-glm switch-libjpeg-turbo devkitARM devkitarm-rules hactool

      - name: get ubuntu version 
        run: | 
          cat /etc/os-release
          ldd --version ldd
     
      # this works but too much time...  
      # - name: install python and pip 
        # run: | 
          # sudo apt-get update
          # sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
          # wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          # tar xzf Python-2.7.18.tgz
          # cd Python-2.7.18
          # ./configure  
          # sudo make 
          # sudo make install
          # cd ..
          # ##sudo apt -y install python-pip
          # curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          # python get-pip.py   
          
      - name: python install
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y python3 python3-lz4          
                    
      # - name: Install dependencies
        # run: python -m pip install --upgrade pip lz4     
      
      # - name: python / nproc test
        # run: | 
          # python --version
          # nproc 
        
      # - name: run fusee python script
        # run: |
          # cd fusee/program/
          # python update_mtc_tables.py
          # python update_sdram_params.py
          # cd ../..
        
      - name: make 
        run: | 
          git config --global --add safe.directory /__w/Atmosphere/Atmosphere 
          cd troposphere/haze
          make -j$(nproc)
          cd ../..
          make -j$(nproc)
          
      - name: get date/date 
        env:
          TZ: "America/Chicago"
        run: | 
          echo "NOW=$(date +'%m-%d-%Y-%I.%M.%S.%p')" >> $GITHUB_ENV          

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: ${{ github.workspace }}/out/nintendo_nx_arm64_armv8a
     
      - name: list out dir
        run: |  
          ls -la
          ls -la out/nintendo_nx_arm64_armv8a
          ls -la out/nintendo_nx_arm64_armv8a/release
           
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NOW }}
          prerelease: false
          draft: false
          body: ${{ github.event.head_commit.message }}
          files: ${{ github.workspace }}/out/nintendo_nx_arm64_armv8a/release/*.*
          name: "Switch Release #${{ env.NOW }}"

        
